### ISSUE TITLE
feature request: expose Join_control and Hangul_Syllable_Type

### ISSUE THREAD

**Issue by hannesm** [dbuenzli/uucp#12]
I started to work on a [PRECIS](https://tools.ietf.org/html/rfc8264) "Preparation, Enforcement, and Comparison of Internationalized Strings in Application Protocols" implementation in OCaml using uucp - PRECIS is used in e.g. SASL authentication to deal with unicode usernames and passwords.  It defines a "derived property" of unicode codepoints, which specifies whether it is allowed (as username (very limited codepoints) or password (lots of codepoints are allowed to allow high entropy)).  This property relies on unicode properties, including `Junk_control` (which require a join context rule) and `Hangul_Syllable_Type` (of which `L`, `T`, and `V` are disallowed).

I figured out that uucd contains types and infrastructure for both above mentioned categories, but uucp does not.  Would you mind adding them to uucp?  If you prefer, I can try to extend uucp and open a PR.

**Comment by dbuenzli** [comment]
There is no `Junk_control` normative property (can't either find a reference to that token in the document you link to). Please point me to the definitions.

Regarding `L`, `V`, `T` if you really need only those (and not `LV` and `LVT`), note that the [ranges](http://www.unicode.org/Public/UCD/latest/ucd/HangulSyllableType.txt) are quite simple and unlikely to change. If you need the full property though I will gladly add it.

**Comment by hannesm** [comment]
@dbuenzli yes, `L`, `V`, and `T` are the only ones I need, thanks.  I'd appreciate to have these ranges defined only once (and thus uucp providing the full property).

sorry for my typo, I meant [`Join_control`](https://www.unicode.org/reports/tr44/#Join_Control), not `Junk_control`.

**Comment by dbuenzli** [comment]
Note that `Join_control` is only [two scalar values](http://cldr-build.unicode.org/UnicodeJsps/list-unicodeset.jsp?a=[:Join_Control=Yes:]).

**Comment by dbuenzli** [comment]
Wishes are on master.

**Comment by hannesm** [comment]
thanks @dbuenzli!
