### ISSUE TITLE
Typo in doc

### ISSUE THREAD

**Issue by sagotch** [dbuenzli/uucp#18]
Hi.

I noticed that `is_hex_digit` doc has a typo. It is written `is_ascii_hex_digit` instead of `is_hex_digit`.

https://github.com/dbuenzli/uucp/blob/0d50ec65c56075f179b96c5348c9bcecfd830d91/src/uucp.mli#L1125-L1128

Cheers.

**Comment by dbuenzli** [comment]
Thanks !
