### ISSUE TITLE
Use the new "module aliases" feature to reduce the size of Uucp

### ISSUE THREAD

**Issue by whitequark** [dbuenzli/uucp#2]
Currently, using any module from Uucp links in all the data, which somewhat bloats the file. The 4.02 module aliases feature would allow to only link the data that is actually used.

**Comment by pqwy** [comment]
Maybe you should revisit this. Anything using `notty` starts at about 7.5 MB in size.

This, while agreeing that aliases multiply names instead of solving namespacing.

**Comment by pqwy** [comment]
@dbuenzli [pingu](http://static.tvtropes.org/pmwiki/pub/images/pingu_506.jpg)

**Comment by dbuenzli** [comment]
Cute.

**Comment by pqwy** [comment]
Any plans here?

**Comment by dbuenzli** [comment]
https://github.com/dbuenzli/uucp/issues/2#issuecomment-66455053

**Comment by pqwy** [comment]
> This was planned and uucp was explicitly designed with that feature in mind
> [...]
> So that won't happen immediately, but it will eventually.

That was over a year ago. Do you have any more concrete plans, that you can commit to?

**Comment by dbuenzli** [comment]
> That was over a year ago. Do you have any more concrete plans, that you can commit to?

I fully commit to the plan outlined in that comment. If you are not able to read was it written there it is basically wait that 4.03 is out, and see if it the documentation problem is solved. 

Besides in which context are these 7.5mo a problem ?

**Comment by pqwy** [comment]
In the context of the entire Unicode character database being grafted onto executables which display a progress bar. It makes me uncomfortable even expressing the idea to people.

Now, even for a pretty comprehensive Unicode treatment, I only need on `Break` (directly and via `uuseg`), `Gc` (via `Break` and `uuseg`), and `White` (`uuseg`). Compiled data for these three comes to about 1MB, something I'm far more comfortable with imposing downstream.

**Comment by nojb** [comment]
Friendly ping. Five years later, what is the status of this?

**Comment by dbuenzli** [comment]
I'll consider doing this for the next Unicode release.

**Comment by nojb** [comment]
> I'll consider doing this for the next Unicode release.

Thanks!

**Comment by whitequark** [comment]
Thanks @dbuenzli!

**Comment by dbuenzli** [comment]
Well that was a long wait 😬.
