### ISSUE TITLE
Wrong computation of unicode table size

### ISSUE THREAD

**Issue by jtristan** [dbuenzli/uucp#26]
I think you may be missing parenthesis in the [definition of tmapbool](https://github.com/dbuenzli/uucp/blob/51e5874c737eca7d7f32b46085d7b9ddec36ad01/src/uucp_tmapbool.ml#L20#L20)

It may cause your innermost tables to be [larger than necessary and filled with unnecessary default values](https://github.com/dbuenzli/uucp/blob/51e5874c737eca7d7f32b46085d7b9ddec36ad01/src/uucp_alpha_data.ml).

**Comment by dbuenzli** [comment]
Good catch ! Thanks for the report. I'll fix that for the next Unicode release in autumn.

**Comment by dbuenzli** [comment]
Thanks, FTR that decreased the binary data in `uucp.a` by ~220KB (2.7%).
