### ISSUE TITLE
API for getting a uchar according to it's name

### ISSUE THREAD

**Issue by marklrh** [dbuenzli/uucp#4]
It seems in ``Name`` module, there is no API that will get a uchar by its name. Is it possible to add one?

**Comment by marklrh** [comment]
In Python 3.4 lexer, when processing ''\N{BASEBALL}', I'd like to have ``⚾`` returned

**Comment by dbuenzli** [comment]
> Is it possible to add one?

It is, but requires care to implement an efficient and memory compact representation. So unlikely to happen soon. Meanwhile you can use something like this: 

```ocaml
let uchar_of_name =
  let module Smap = Map.Make (String) in
  let add_name acc u = Smap.add (Uucp.Name.name u) u acc in
  let ndb = Uucp.Uchar.fold add_name Smap.empty in
  fun n -> try Some (Smap.find n ndb) with Not_found -> None
```

It takes approximatively 385ms to build the map on my machine, but maybe you can simply cache it somewhere.

**Comment by marklrh** [comment]
Thanks. Since this kind of lexeme shows up rarely, I'll use ``lazy`` to build map only when it's actually used.
